### ISSUE TITLE
As a user i can write my email and password on the log in form

### ISSUE THREAD

**Issue by violetapintoleite** [violetapintoleite/chore-manager-app#11]
<img width="889" alt="Screenshot 2022-07-01 at 08 40 43" src="https://user-images.githubusercontent.com/48143282/176848418-621aa7f6-ec22-42c7-9c6c-9d7fba2bec7f.png">

**Comment by violetapintoleite** [comment]
there is also a close button to leave the log in form (redirect back to the home page)

**Comment by christianmartinroffey** [comment]
dupe - added screenshot and comment to #15
