### ISSUE TITLE
As a user I can see the log in button on the home page

### ISSUE THREAD

**Issue by violetapintoleite** [violetapintoleite/chore-manager-app#2]
<img width="951" alt="Screenshot 2022-07-01 at 10 03 19" src="https://user-images.githubusercontent.com/48143282/176862939-f7e9aec1-03ff-45b7-aa50-33da293d41e4.png">

**Comment by rnuru002** [comment]
nice work so far :)

**Comment by christianmartinroffey** [comment]
closing as a dupe of #20 

added screenshot to #20
